### ISSUE TITLE
configure works, but make fails due to lack of com directory

### ISSUE THREAD

**Issue by 831Mark** [SirWumpus/libsnert#2]
Checked out the git repository for libsnert.  

Running configure appears to work without issue, Make fails with the following:

`
***************************************************************
==> /usr/local/src/libsnert
***************************************************************

gcc  -O2 -Wall -Wno-unused -Wno-char-subscripts -m64 -I./../../include -c LibSnert.c
LibSnert.c:7:10: fatal error: com/snert/lib/version.h: No such file or directory
 #include <com/snert/lib/version.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:103: LibSnert.o] Error 1
`
There doesn't appear to be a "com" directory in the file structure?

**Comment by SirWumpus** [comment]
This is an artefact of working with Java 4/6 to build a JNI library using libsnert from years back (around 2002) and prior to GitHub only distributing libsnert as a tarball with the correct tree saved.  

The current work around (and maybe the solution to be documented):

```
mkdir -p com/snert/src
cd com/snert/src
git clone https://github.com/SirWumpus/libsnert.git lib
cd lib
./configure
make links       # need only happen once
make
```
